import { Navbar } from '@/components'
import './globals.css'
import 'react-toastify/dist/ReactToastify.min.css';
import type { Metadata } from 'next'
import { Nunito,Montserrat } from 'next/font/google'

const montserrat=Montserrat({subsets:['latin'],variable:'--font-display'});
const nunito=Nunito({subsets:['latin'],variable:'--font-body'})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">      
      <body className={`${montserrat.variable} ${nunito.variable} font-body selection:text-primary-200 selection:bg-primary-800 bg-primary-100`}><Navbar/>{children}</body>
    </html>
  )
}
